name: housekeep
description: "Inventario domestico — FASE 1 prodotti."
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  path: ^1.9.0
  intl: any
  uuid: ^4.5.1
  fl_chart: ^0.69.0
  pdf: ^3.11.1
  printing: ^5.13.3
  share_plus: ^10.1.2
  mobile_scanner: ^5.2.3
  image_picker: ^1.1.2
  image: ^4.2.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  flutter_timezone: ^5.0.2
  permission_handler: ^11.3.1
  lottie: ^3.1.2
  simple_animations: ^5.0.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  mocktail: ^1.0.4
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/google_fonts/
